### ISSUE TITLE
New Course - Recoding: Transforming Data into Different Structures

### ISSUE THREAD

**Issue by Buffett65** [SDMX-Outreach/sdmx-learning-catalogue#10]
### Contact Details

contact.sdmx.io@bis.org

### Course title

Recoding: Transforming Data into Different Structures

### Topic

- [X] SDMX data modelling
- [ ] Labour statistics
- [ ] European National Accounts
- [ ] SDGs
- [ ] SDMX tools
- [ ] .Stat Suite
- [X] Fusion Metadata Registry
- [ ] SDMX Matrix Generator
- [ ] SDMX Converter
- [ ] Euro SDMX Registry
- [ ] Other - suggest a new topic

### Course type

elearning, self-paced

### Course price

Free

### Summary

Throughout their lifecycle, data are subjected to many operations and transformations as they are massaged, aggregated, summarised, analysed, and customised for a wide range of outputs. The primary focus of this module is on recoding data using the SDMX standard and **Fusion Metadata Registry (FMR)**.

### Sponsor

BIS

### The URL of your course

https://www.sdmx.io/resources/elearning/recoding-transforming-data-into-different-structures/

### The URL of an image for your course

https://sdmx.io/images/elearning/card-recoding-data.png

**Comment by Buffett65** [comment]
This issue has been sitting here for some time. Assigning everyone as the process is unclear. Thanks, Brian

**Comment by Buffett65** [comment]
please publish

**Comment by OSoerensen** [comment]
@glenntav @ChallenerSJ I have created this pull request yesterday https://github.com/SDMX-Outreach/sdmx-learning-catalogue/pull/16 could you please review it.

**Comment by OSoerensen** [comment]
Please do it from down and up so 14, 15, 16, 17

**Comment by OSoerensen** [comment]
request merged
