### ISSUE TITLE
New Course - Data Collection with XLSX Templates: All about XLSX Templates

### ISSUE THREAD

**Issue by Buffett65** [SDMX-Outreach/sdmx-learning-catalogue#11]
### Contact Details

contact.sdmx.io@bis.org

### Course title

Data Collection with XLSX Templates: All about XLSX Templates

### Topic

- [ ] SDMX data modelling
- [ ] Labour statistics
- [ ] European National Accounts
- [ ] SDGs
- [ ] SDMX tools
- [ ] .Stat Suite
- [X] Fusion Metadata Registry
- [ ] SDMX Matrix Generator
- [ ] SDMX Converter
- [ ] Euro SDMX Registry
- [X] Other - suggest a new topic

### Suggest a new topic if needed

Data Collection

### Course type

elearning, self-paced

### Course price

Free

### Summary

Statistical agencies, Central Banks, and other data-driven organisations need to collect data. MS Excel is a common tool used for this purpose.
Metadata driven MS XLSX documents enable data collectors to design and run efficient data collection processes in accordance with the SDMX structural model. This approach makes it easier to validate, to integrate these data into production workflows, and to improve data quality. 

### Sponsor

BIS

### The URL of your course

https://www.sdmx.io/resources/elearning/data-collection-with-xlsx-templates-all-about-xlsx-templates/

### The URL of an image for your course

https://sdmx.io/images/elearning/card-data-collection-with-xlsx-templates.png

**Comment by Buffett65** [comment]
This issue has been sitting here for some time. Assigning everyone as the process is unclear. Thanks, Brian

**Comment by Buffett65** [comment]
please publish

**Comment by ChallenerSJ** [comment]
@Buffett65, I only just received a notification when you assigned me today. We should agree who will monitor this to avoid having to do that.

**Comment by OSoerensen** [comment]
@Buffett65 @ChallenerSJ yes, same here, did not notice the issues before now. I can monitor it, trying to check once a week, that should be enough. I will take care of the created issues

**Comment by OSoerensen** [comment]
@glenntav @ChallenerSJ  I have created this pull request yesterday https://github.com/SDMX-Outreach/sdmx-learning-catalogue/pull/17 could you please review it.

**Comment by OSoerensen** [comment]
Please do it from down and up so 14, 15, 16, 17

**Comment by OSoerensen** [comment]
Request merged
