### ISSUE TITLE
Broken Links 

### ISSUE THREAD

**Issue by Buffett65** [SDMX-Outreach/sdmx-learning-catalogue#12]
Link on this page: https://github.com/SDMX-Outreach/sdmx-learning-catalogue/blob/main/README.md

Link: https://sdmx.org/learning/
Should link to https://sdmx.org/?page_id=2555
But doesn't.

Thanks,
Brian

**Comment by ChallenerSJ** [comment]
Fixed and pull request submitted for review #13

**Comment by OSoerensen** [comment]
Issue fixed, closing it.
