### ISSUE TITLE
New Course - Essential SDMX and the Fusion Metadata Registry (FMR)

### ISSUE THREAD

**Issue by Buffett65** [SDMX-Outreach/sdmx-learning-catalogue#8]
### Contact Details

contact.sdmx.io@bis.org

### Course title

Essential SDMX and the Fusion Metadata Registry (FMR)

### Topic

- [X] SDMX data modelling
- [ ] Labour statistics
- [ ] European National Accounts
- [ ] SDGs
- [ ] SDMX tools
- [ ] .Stat Suite
- [X] Fusion Metadata Registry
- [ ] SDMX Matrix Generator
- [ ] SDMX Converter
- [ ] Euro SDMX Registry
- [ ] Other - suggest a new topic

### Course type

elearning, self-paced

### Course price

Free

### Summary

Building upon the knowledge and skills previously acquired regarding SDMX structural modelling, this module introduces practical knowledge on how to create and manage an SDMX structural model using the **Fusion Metadata Registry (FMR)**.

### Sponsor

BIS

### The URL of your course

https://www.sdmx.io/resources/elearning/essential-sdmx-and-the-fusion-metadata-registry/

### The URL of an image for your course

https://sdmx.io/images/elearning/card-essential-sdmx-n-fmr.png

**Comment by Buffett65** [comment]
This issue has been sitting here for some time. Assigning everyone as the process is unclear. Thanks, Brian

**Comment by Buffett65** [comment]
Please publish.

**Comment by OSoerensen** [comment]
@glenntav  @ChallenerSJ  I have created this pull request https://github.com/SDMX-Outreach/sdmx-learning-catalogue/pull/14 yesterday could you please review it.

**Comment by OSoerensen** [comment]
Please do it from down and up so 14, 15, 16, 17

**Comment by OSoerensen** [comment]
Request merged
