### ISSUE TITLE
New Course - FMR Pro Tips

### ISSUE THREAD

**Issue by Buffett65** [SDMX-Outreach/sdmx-learning-catalogue#9]
### Contact Details

contact.sdmx.io@bis.org

### Course title

Fusion Metadata Registry (FMR) Pro Tips

### Topic

- [X] SDMX data modelling
- [ ] Labour statistics
- [ ] European National Accounts
- [ ] SDGs
- [ ] SDMX tools
- [ ] .Stat Suite
- [X] Fusion Metadata Registry
- [ ] SDMX Matrix Generator
- [ ] SDMX Converter
- [ ] Euro SDMX Registry
- [ ] Other - suggest a new topic

### Course type

elearning, self-paced

### Course price

Free

### Summary

The **Fusion Metadata Registry (FMR)** is a SDMX v2.0, v2.1, and v3.0 compliant structural metadata registry with an extensive set of features. This module is a collection of tips to highlight some of these capabilities and practical ideas on how to use the tool to accomplish your structural metadata maintenance tasks in an efficient manner.

### Sponsor

BIS

### The URL of your course

https://www.sdmx.io/resources/elearning/fusion-metadata-registry-fmr-pro-tips/

### The URL of an image for your course

https://sdmx.io/images/elearning/card-fmr-pro-tips.png

**Comment by Buffett65** [comment]
This issue has been sitting here for some time. Assigning everyone as the process is unclear. Thanks, Brian

**Comment by Buffett65** [comment]
please publish

**Comment by OSoerensen** [comment]
@glenntav @ChallenerSJ  I have created this pull request https://github.com/SDMX-Outreach/sdmx-learning-catalogue/pull/15 yesterday, could you please review it

**Comment by OSoerensen** [comment]
Please do it from down and up so 14, 15, 16, 17

**Comment by OSoerensen** [comment]
Request merged
